### ISSUE TITLE
NullPointerException when running crosschecking with HornDroid

### ISSUE THREAD

**Issue by zjbthomas** [FoelliX/CoDiDroid#2] opened 2020-12-06 01:29 UTC
Hi @FoelliX,

My setup: FlowDroid2 (version 2.7.1), HornDroid, IC3, and DroidRA in an AQL-system.

When I ran the following query (for apps in DroidBench 3.0) there is nothing wrong so I believe my setup is correct:
```
CONNECT [
         Flows IN App('/path/to/apk' | 'DEOBFUSCATE') ?,
         IntentSinks IN App('/path/to/apk' | 'DEOBFUSCATE') ?,
         IntentSources IN App('/path/to/apk' | 'DEOBFUSCATE') ?
]
```

However, when I ran the following query with crosschecking, there are `NullPointerException`s for almost all apps in DroidBench 3.0.
```
CHECK [
        CONNECT [
            Flows IN App('/path/to/apk' | 'DEOBFUSCATE') ?,
            IntentSinks IN App('/path/to/apk' | 'DEOBFUSCATE') ?,
            IntentSources IN App('/path/to/apk' | 'DEOBFUSCATE') ?
        ],
        CONNECT [
            Flows IN App('/path/to/apk' | 'DEOBFUSCATE') USES 'HornDroid' ?,
            IntentSinks IN App('/path/to/apk' | 'DEOBFUSCATE') ?,
            IntentSources IN App('/path/to/apk' | 'DEOBFUSCATE') ?
        ]
]
```

I also attached a log output from the AQL-system on Aliasing/FlowSensitivity1 in DroidBench 3.0. It seems like all tools can be executed successfully. So I think maybe there is an issue when AQL-system performs `CHECK` operation?

[log.txt](https://github.com/FoelliX/CoDiDroid/files/5648141/log.txt)

The error did not point me to a concrete place in the source code so I am sorry I cannot debug it myself. Could you please have a look and provide some suggestions? Thank you in advance!

**Comment by FoelliX** [comment] 2020-12-07 07:29
Hi @zjbthomas,

is the ``CHECK`` Operator present in your AQL-System's config file anyway?
Guess not since I just realized, that I never pushed it.
It is available now: https://github.com/FoelliX/AQL-CheckOperator

Sorry, hope it helps!

Regards,
FoelliX

**Comment by zjbthomas** [comment] 2020-12-07 20:33
Hi @FoelliX ,

Adding `CHECK` to the config file with the provided CheckOperator removes the exception. Many thanks!

Though, I noticed that the `%ANSWERS%` in `<run>java -jar /path/to/AQL-CheckOperator-0.1.0.jar %ANSWERS%</run>` is replaced to be "NOT_AVAILABLE", aborting the analysis with the following exception. Could you please let me know any possible reason?

```
Exception in thread "Thread-62" java.lang.IllegalArgumentException: obj parameter must not be null
        at javax.xml.bind.helpers.AbstractMarshallerImpl.checkNotNull(AbstractMarshallerImpl.java:438)
        at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:94)
        at de.foellix.aql.datastructure.handler.AnswerHandler.createXML(AnswerHandler.java:95)
        at de.foellix.aql.system.System.operatorExecuted(System.java:207)
        at de.foellix.aql.system.Scheduler.finishedTask(Scheduler.java:272)
        at de.foellix.aql.system.task.Task.run(Task.java:68)
```

Just for your information: I noticed that in the config for PIM there is also `%ANSWERS%`. When I run PIM this placeholder can be successfully converted to temp files inside /data/temp.

**Comment by FoelliX** [comment] 2020-12-08 07:54
Hi @zjbthomas,

it seems that the AQL-System is not able to read one of the AQL-Answers generated by converting the result of one of the analysis tools. Just tested with the following query:
```
CHECK [
	CONNECT [
		Flows IN App('DirectLeak1.apk') ?,
		Flows IN App('DirectLeak1.apk') ?
	],
	CONNECT [
		Flows IN App('DirectLeak1.apk') ?,
		Flows IN App('DirectLeak1.apk') ?
	]
]
```
Does a similar query work for you? Than it should not be caused by the CHECK operator.

Here are some hints to find the answer that is not generated successfully:
- remember to set debugging log level: "-d detailed"
- checking the original result path (see config - ``<result>/path/to/result</result>``)
- running tools one by one (one part of the query after another)

Let me know if you found the error. If you cannot find it probably post the whole log again.

Cheers,
FoelliX

**Comment by zjbthomas** [comment] 2020-12-08 19:40
Hi @FoelliX .

Is it possible that the error happens at `CONNECT` when there is no IntentSink and IntentSource in an app?

I attached the logs for the following two query:

```
CHECK [
        CONNECT [
            Flows IN App('/path/to/apk' | 'DEOBFUSCATE') ?
        ],
        CONNECT [
            Flows IN App('/path/to/apk' | 'DEOBFUSCATE') USES 'HornDroid' ?
        ]
]
```

[log_noIC3.txt](https://github.com/FoelliX/CoDiDroid/files/5661486/log_noIC3.txt)

```
CHECK [
        CONNECT [
            Flows IN App('/path/to/apk' | 'DEOBFUSCATE') ?,
            IntentSinks IN App('/path/to/apk' | 'DEOBFUSCATE') ?,
            IntentSources IN App('/path/to/apk' | 'DEOBFUSCATE') ?
        ],
        CONNECT [
            Flows IN App('/path/to/apk' | 'DEOBFUSCATE') USES 'HornDroid' ?,
            IntentSinks IN App('/path/to/apk' | 'DEOBFUSCATE') ?,
            IntentSources IN App('/path/to/apk' | 'DEOBFUSCATE') ?
        ]
]
```

[log_IC3.txt](https://github.com/FoelliX/CoDiDroid/files/5661489/log_IC3.txt)

In the second one there is an NullPointerException when using `-d detailed`.
```
java.lang.NullPointerException
	at de.foellix.aql.helper.EqualsHelper.equals(EqualsHelper.java:345)
	at de.foellix.aql.helper.EqualsHelper.equals(EqualsHelper.java:84)
	at de.foellix.aql.helper.Helper.removeRedundant(Helper.java:1061)
	at de.foellix.aql.system.DefaultOperatorInstance.unify(DefaultOperatorInstance.java:179)
	at de.foellix.aql.system.DefaultOperatorInstance.connect(DefaultOperatorInstance.java:189)
	at de.foellix.aql.system.DefaultOperatorInstance.connect(DefaultOperatorInstance.java:185)
	at de.foellix.aql.system.DefaultOperatorInstance.applyOperator(DefaultOperatorInstance.java:91)
	at de.foellix.aql.system.DefaultOperator.applyOperator(DefaultOperator.java:12)
	at de.foellix.aql.system.task.OperatorTask.execute(OperatorTask.java:43)
	at de.foellix.aql.system.task.Task.run(Task.java:54)
```

**Comment by FoelliX** [comment] 2020-12-09 07:30
Hi @zjbthomas,

the null pointer is causing it. Fixed it in AQL-System's develop branch. Anyway, it was also fixed in the new AQL-System version which is not released, yet.
Fow now, I attached an updated build to this message ([snapshot-develop.zip](https://github.com/FoelliX/CoDiDroid/files/5664163/snapshot-develop.zip)).

Cheers,
FoelliX

**Closed as completed** 2020-12-11 06:36 UTC
Labels: bug
